stages:
  - install_npm_dependencies

build_job:
  stage: install_npm_dependencies
  tags:
    - Gitlab_EC2_runner
  script:
    - sudo apt install nodejs -y
    - sudo apt install npm -y
    - npm install





  

