stages:
  - install_npm_dependencies
  - sonarcloud_analysis
  - docker_build
  - trivy_scan


variables:
  SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar" 
  GIT_DEPTH: "0" 


build_job:
  stage: install_npm_dependencies
  tags:
    - Gitlab_EC2_runner
  script:
    - sudo apt install nodejs -y
    - sudo apt install npm -y
    - sudo apt install docker.io -y && sudo chmod 666 /var/run/docker.sock
    - npm install


sonarcloud-check:
  stage: sonarcloud_analysis
  image:
    name: sonarsource/sonar-scanner-cli:latest
    entrypoint: [""]
  cache:
    key: "${CI_JOB_NAME}"
    paths:
      - .sonar/cache
  script:
    - sonar-scanner
  only:
    - merge_requests
    - main

docker_build_job:
  stage: docker_build
  script: 
    - docker build -t repo-name:$CI_COMMIT_SHA .
  only:
    - main
  tags:
    - Gitlab_EC2_runner

image_scan_job:
  srage: trivy_scan
  script:
    - docker run -v /var/run/docker.sock:/var/run/docker.sock -v $Home/Library/Caches:/root/.cache/ aquasec/trivy:0.57.0 image repo-name:$CI_COMMIT_SHA 
  only: 
    -main
  tags:
    - Gitlab_EC2_runner
